#pragma once

#include "../result.h"
#include "../api.h"
#include "../typedefs.h"

#if defined( MOTOR_TARGET_OS_WIN )
#include <windows.h>
#elif defined( MOTOR_TARGET_OS_LIN )
#else
#endif

#include <GL/glcorearb.h>
//#define GL_VERSION_1_1 0

#include <list>

namespace motor
{
    namespace ogl
    {
        struct MOTOR_OGL_API gl
        {
            motor_this_typedefs( gl ) ;

        public:

            typedef std::list< char_t const * > string_list_t ;
            static string_list_t _extensions ;            

            static bool_t _init ;

        public:

            static motor::ogl::result init( void_t ) ;

            static bool_t is_supported( char const* name ) ;
        };
    }
}

#if 0
namespace motor
{
    namespace ogl
    {
        #endif
    // gl version 1.0

        MOTOR_OGL_API_C PFNGLCULLFACEPROC glCullFace ;
        MOTOR_OGL_API_C PFNGLFRONTFACEPROC glFrontFace ;
        MOTOR_OGL_API_C PFNGLHINTPROC glHint ;
        MOTOR_OGL_API_C PFNGLLINEWIDTHPROC glLineWidth;
        MOTOR_OGL_API_C PFNGLPOINTSIZEPROC glPointSize ;
        MOTOR_OGL_API_C PFNGLPOLYGONMODEPROC glPolygonMode ;
        MOTOR_OGL_API_C PFNGLSCISSORPROC glScissor ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERFPROC glTexParameterf ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERFVPROC glTexParameterfv ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERIPROC glTexParameteri ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERIVPROC glTexParameteriv ;
        MOTOR_OGL_API_C PFNGLTEXIMAGE1DPROC glTexImage1D ;
        MOTOR_OGL_API_C PFNGLTEXIMAGE2DPROC glTexImage2D ;
        MOTOR_OGL_API_C PFNGLDRAWBUFFERPROC glDrawBuffer ;
        MOTOR_OGL_API_C PFNGLCLEARPROC glClear ;
        MOTOR_OGL_API_C PFNGLCLEARCOLORPROC glClearColor ;
        MOTOR_OGL_API_C PFNGLCLEARSTENCILPROC glClearStencil ;
        MOTOR_OGL_API_C PFNGLCLEARDEPTHPROC glClearDepth ;
        MOTOR_OGL_API_C PFNGLSTENCILMASKPROC glStencilMask ;
        MOTOR_OGL_API_C PFNGLCOLORMASKPROC glColorMask ;
        MOTOR_OGL_API_C PFNGLDEPTHMASKPROC glDepthMask ;
        MOTOR_OGL_API_C PFNGLDISABLEPROC glDisable ;
        MOTOR_OGL_API_C PFNGLENABLEPROC glEnable ;
        MOTOR_OGL_API_C PFNGLFINISHPROC glFinish ;
        MOTOR_OGL_API_C PFNGLFLUSHPROC glFlush ;
        MOTOR_OGL_API_C PFNGLBLENDFUNCPROC glBlendFunc ;
        MOTOR_OGL_API_C PFNGLLOGICOPPROC glLogicOp ;
        MOTOR_OGL_API_C PFNGLSTENCILFUNCPROC glStencilFunc ;
        MOTOR_OGL_API_C PFNGLSTENCILOPPROC glStencilOp ;
        MOTOR_OGL_API_C PFNGLDEPTHFUNCPROC glDepthFunc ;
        MOTOR_OGL_API_C PFNGLPIXELSTOREFPROC glPixelStoref ;
        MOTOR_OGL_API_C PFNGLPIXELSTOREIPROC glPixelStorei ;
        MOTOR_OGL_API_C PFNGLREADBUFFERPROC glReadBuffer ;
        MOTOR_OGL_API_C PFNGLREADPIXELSPROC glReadPixels ;
        MOTOR_OGL_API_C PFNGLGETBOOLEANVPROC glGetBooleanv ;
        MOTOR_OGL_API_C PFNGLGETDOUBLEVPROC glGetDoublev ;
        MOTOR_OGL_API_C PFNGLGETERRORPROC glGetError ;
        MOTOR_OGL_API_C PFNGLGETFLOATVPROC glGetFloatv ;
        MOTOR_OGL_API_C PFNGLGETINTEGERVPROC glGetIntegerv ;
        MOTOR_OGL_API_C PFNGLGETSTRINGPROC glGetString ;
        MOTOR_OGL_API_C PFNGLGETTEXIMAGEPROC glGetTexImage ;
        MOTOR_OGL_API_C PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv ;
        MOTOR_OGL_API_C PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv ;
        MOTOR_OGL_API_C PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv ;
        MOTOR_OGL_API_C PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv ;
        MOTOR_OGL_API_C PFNGLISENABLEDPROC glIsEnabled ;
        MOTOR_OGL_API_C PFNGLDEPTHRANGEPROC glDepthRange ;
        MOTOR_OGL_API_C PFNGLVIEWPORTPROC glViewport ;

    // gl version 1.1

        MOTOR_OGL_API_C PFNGLDRAWARRAYSPROC glDrawArrays ;
        MOTOR_OGL_API_C PFNGLDRAWELEMENTSPROC glDrawElements ;
        MOTOR_OGL_API_C PFNGLGETPOINTERVPROC glGetPointerv ;
        MOTOR_OGL_API_C PFNGLPOLYGONOFFSETPROC glPolygonOffset ;
        MOTOR_OGL_API_C PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D ;
        MOTOR_OGL_API_C PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D ;
        MOTOR_OGL_API_C PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D ;
        MOTOR_OGL_API_C PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D ;
        MOTOR_OGL_API_C PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D ;
        MOTOR_OGL_API_C PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D ;
        MOTOR_OGL_API_C PFNGLBINDTEXTUREPROC glBindTexture ;
        MOTOR_OGL_API_C PFNGLDELETETEXTURESPROC glDeleteTextures ;
        MOTOR_OGL_API_C PFNGLGENTEXTURESPROC glGenTextures ;
        MOTOR_OGL_API_C PFNGLISTEXTUREPROC glIsTexture ;

    // gl version 1.2

        MOTOR_OGL_API_C PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements ;
        MOTOR_OGL_API_C PFNGLTEXIMAGE3DPROC glTexImage3D ;
        MOTOR_OGL_API_C PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D ;
        MOTOR_OGL_API_C PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D ;

    // gl version 1.3

        MOTOR_OGL_API_C PFNGLACTIVETEXTUREPROC glActiveTexture ;
        MOTOR_OGL_API_C PFNGLSAMPLECOVERAGEPROC glSampleCoverage ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D ;
        MOTOR_OGL_API_C PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D ;
        MOTOR_OGL_API_C PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage ;

    // gl version 1.4

        MOTOR_OGL_API_C PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate ;
        MOTOR_OGL_API_C PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays ;
        MOTOR_OGL_API_C PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements ;
        MOTOR_OGL_API_C PFNGLPOINTPARAMETERFPROC glPointParameterf ;
        MOTOR_OGL_API_C PFNGLPOINTPARAMETERFVPROC glPointParameterfv ;
        MOTOR_OGL_API_C PFNGLPOINTPARAMETERIPROC glPointParameteri ;
        MOTOR_OGL_API_C PFNGLPOINTPARAMETERIVPROC glPointParameteriv ;
        MOTOR_OGL_API_C PFNGLBLENDCOLORPROC glBlendColor ;
        MOTOR_OGL_API_C PFNGLBLENDEQUATIONPROC glBlendEquation ;

    // gl version 1.5

        MOTOR_OGL_API_C PFNGLGENQUERIESPROC glGenQueries  ;
        MOTOR_OGL_API_C PFNGLDELETEQUERIESPROC glDeleteQueries ;
        MOTOR_OGL_API_C PFNGLISQUERYPROC glIsQuery ;
        MOTOR_OGL_API_C PFNGLBEGINQUERYPROC glBeginQuery ;
        MOTOR_OGL_API_C PFNGLENDQUERYPROC glEndQuery ;
        MOTOR_OGL_API_C PFNGLGETQUERYIVPROC glGetQueryiv ;
        MOTOR_OGL_API_C PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv ;
        MOTOR_OGL_API_C PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv ;
        MOTOR_OGL_API_C PFNGLBINDBUFFERPROC glBindBuffer ;
        MOTOR_OGL_API_C PFNGLDELETEBUFFERSPROC glDeleteBuffers ;
        MOTOR_OGL_API_C PFNGLGENBUFFERSPROC glGenBuffers ;
        MOTOR_OGL_API_C PFNGLISBUFFERPROC glIsBuffer ;
        MOTOR_OGL_API_C PFNGLBUFFERDATAPROC glBufferData ;
        MOTOR_OGL_API_C PFNGLBUFFERSUBDATAPROC glBufferSubData ;
        MOTOR_OGL_API_C PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData ;
        MOTOR_OGL_API_C PFNGLMAPBUFFERPROC glMapBuffer ;
        MOTOR_OGL_API_C PFNGLUNMAPBUFFERPROC glUnmapBuffer ;
        MOTOR_OGL_API_C PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv ;
        MOTOR_OGL_API_C PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv ;

    // gl version 2.0

        MOTOR_OGL_API_C PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate  ;
        MOTOR_OGL_API_C PFNGLDRAWBUFFERSPROC glDrawBuffers ;
        MOTOR_OGL_API_C PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate ;
        MOTOR_OGL_API_C PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate ;
        MOTOR_OGL_API_C PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate ;
        MOTOR_OGL_API_C PFNGLATTACHSHADERPROC glAttachShader ;
        MOTOR_OGL_API_C PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation ;
        MOTOR_OGL_API_C PFNGLCOMPILESHADERPROC glCompileShader ;
        MOTOR_OGL_API_C PFNGLCREATEPROGRAMPROC glCreateProgram ;
        MOTOR_OGL_API_C PFNGLCREATESHADERPROC glCreateShader ;
        MOTOR_OGL_API_C PFNGLDELETEPROGRAMPROC glDeleteProgram ;
        MOTOR_OGL_API_C PFNGLDELETESHADERPROC glDeleteShader ;
        MOTOR_OGL_API_C PFNGLDETACHSHADERPROC glDetachShader ;
        MOTOR_OGL_API_C PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray ;
        MOTOR_OGL_API_C PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray ;
        MOTOR_OGL_API_C PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib ;
        MOTOR_OGL_API_C PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform ;
        MOTOR_OGL_API_C PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders ;
        MOTOR_OGL_API_C PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMIVPROC glGetProgramiv ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog ;
        MOTOR_OGL_API_C PFNGLGETSHADERIVPROC glGetShaderiv ;
        MOTOR_OGL_API_C PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog ;
        MOTOR_OGL_API_C PFNGLGETSHADERSOURCEPROC glGetShaderSource ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMFVPROC glGetUniformfv ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMIVPROC glGetUniformiv ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv ;
        MOTOR_OGL_API_C PFNGLISPROGRAMPROC glIsProgram ;
        MOTOR_OGL_API_C PFNGLISSHADERPROC glIsShader ;
        MOTOR_OGL_API_C PFNGLLINKPROGRAMPROC glLinkProgram ;
        MOTOR_OGL_API_C PFNGLSHADERSOURCEPROC glShaderSource ;
        MOTOR_OGL_API_C PFNGLUSEPROGRAMPROC glUseProgram ;
        MOTOR_OGL_API_C PFNGLUNIFORM1FPROC glUniform1f ;
        MOTOR_OGL_API_C PFNGLUNIFORM2FPROC glUniform2f ;
        MOTOR_OGL_API_C PFNGLUNIFORM3FPROC glUniform3f ;
        MOTOR_OGL_API_C PFNGLUNIFORM4FPROC glUniform4f ;
        MOTOR_OGL_API_C PFNGLUNIFORM1IPROC glUniform1i ;
        MOTOR_OGL_API_C PFNGLUNIFORM2IPROC glUniform2i ;
        MOTOR_OGL_API_C PFNGLUNIFORM3IPROC glUniform3i ;
        MOTOR_OGL_API_C PFNGLUNIFORM4IPROC glUniform4i ;
        MOTOR_OGL_API_C PFNGLUNIFORM1FVPROC glUniform1fv ;
        MOTOR_OGL_API_C PFNGLUNIFORM2FVPROC glUniform2fv ;
        MOTOR_OGL_API_C PFNGLUNIFORM3FVPROC glUniform3fv ;
        MOTOR_OGL_API_C PFNGLUNIFORM4FVPROC glUniform4fv ;
        MOTOR_OGL_API_C PFNGLUNIFORM1IVPROC glUniform1iv ;
        MOTOR_OGL_API_C PFNGLUNIFORM2IVPROC glUniform2iv ;
        MOTOR_OGL_API_C PFNGLUNIFORM3IVPROC glUniform3iv ;
        MOTOR_OGL_API_C PFNGLUNIFORM4IVPROC glUniform4iv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv ;
        MOTOR_OGL_API_C PFNGLVALIDATEPROGRAMPROC glValidateProgram ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer ;

    // gl version 2.1

        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv ;

    // gl version 3.0

        MOTOR_OGL_API_C PFNGLCOLORMASKIPROC glColorMaski ;
        MOTOR_OGL_API_C PFNGLGETBOOLEANI_VPROC glGetBooleani_v ;
        MOTOR_OGL_API_C PFNGLGETINTEGERI_VPROC glGetIntegeri_v ;
        MOTOR_OGL_API_C PFNGLENABLEIPROC glEnablei ;
        MOTOR_OGL_API_C PFNGLDISABLEIPROC glDisablei ;
        MOTOR_OGL_API_C PFNGLISENABLEDIPROC glIsEnabledi ;
        MOTOR_OGL_API_C PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback ;
        MOTOR_OGL_API_C PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback ;
        MOTOR_OGL_API_C PFNGLBINDBUFFERRANGEPROC glBindBufferRange ;
        MOTOR_OGL_API_C PFNGLBINDBUFFERBASEPROC glBindBufferBase ;
        MOTOR_OGL_API_C PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings ;
        MOTOR_OGL_API_C PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying ;
        MOTOR_OGL_API_C PFNGLCLAMPCOLORPROC glClampColor ;
        MOTOR_OGL_API_C PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender ;
        MOTOR_OGL_API_C PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4SVPROC  glVertexAttribI4sv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMUIVPROC glGetUniformuiv ;
        MOTOR_OGL_API_C PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation ;
        MOTOR_OGL_API_C PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation ;
        MOTOR_OGL_API_C PFNGLUNIFORM1UIPROC glUniform1ui ;
        MOTOR_OGL_API_C PFNGLUNIFORM2UIPROC glUniform2ui ;
        MOTOR_OGL_API_C PFNGLUNIFORM3UIPROC glUniform3ui ;
        MOTOR_OGL_API_C PFNGLUNIFORM4UIPROC glUniform4ui ;
        MOTOR_OGL_API_C PFNGLUNIFORM1UIVPROC glUniform1uiv ;
        MOTOR_OGL_API_C PFNGLUNIFORM2UIVPROC glUniform2uiv ;
        MOTOR_OGL_API_C PFNGLUNIFORM3UIVPROC glUniform3uiv ;
        MOTOR_OGL_API_C PFNGLUNIFORM4UIVPROC glUniform4uiv ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERIIVPROC glTexParameterIiv ;
        MOTOR_OGL_API_C PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv ;
        MOTOR_OGL_API_C PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv ;
        MOTOR_OGL_API_C PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv ;
        MOTOR_OGL_API_C PFNGLCLEARBUFFERIVPROC glClearBufferiv ;
        MOTOR_OGL_API_C PFNGLCLEARBUFFERUIVPROC glClearBufferuiv ;
        MOTOR_OGL_API_C PFNGLCLEARBUFFERFVPROC glClearBufferfv ;
        MOTOR_OGL_API_C PFNGLCLEARBUFFERFIPROC glClearBufferfi ;
        MOTOR_OGL_API_C PFNGLGETSTRINGIPROC glGetStringi ;
        MOTOR_OGL_API_C PFNGLISRENDERBUFFERPROC glIsRenderbuffer ;
        MOTOR_OGL_API_C PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer ;
        MOTOR_OGL_API_C PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers ;
        MOTOR_OGL_API_C PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers ;
        MOTOR_OGL_API_C PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage ;
        MOTOR_OGL_API_C PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv ;
        MOTOR_OGL_API_C PFNGLISFRAMEBUFFERPROC glIsFramebuffer ;
        MOTOR_OGL_API_C PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer ;
        MOTOR_OGL_API_C PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers ;
        MOTOR_OGL_API_C PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers ;
        MOTOR_OGL_API_C PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer ;
        MOTOR_OGL_API_C PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv ;
        MOTOR_OGL_API_C PFNGLGENERATEMIPMAPPROC glGenerateMipmap ;
        MOTOR_OGL_API_C PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer ;
        MOTOR_OGL_API_C PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer ;
        MOTOR_OGL_API_C PFNGLMAPBUFFERRANGEPROC glMapBufferRange ;
        MOTOR_OGL_API_C PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange ;
        MOTOR_OGL_API_C PFNGLBINDVERTEXARRAYPROC glBindVertexArray ;
        MOTOR_OGL_API_C PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays ;
        MOTOR_OGL_API_C PFNGLGENVERTEXARRAYSPROC glGenVertexArrays ;
        MOTOR_OGL_API_C PFNGLISVERTEXARRAYPROC glIsVertexArray ;

    // gl version 3.1

        MOTOR_OGL_API_C PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced ;
        MOTOR_OGL_API_C PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced ;
        MOTOR_OGL_API_C PFNGLTEXBUFFERPROC glTexBuffer ;
        MOTOR_OGL_API_C PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex ;
        MOTOR_OGL_API_C PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMINDICESPROC glGetUniformIndices ;
        MOTOR_OGL_API_C PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv ;
        MOTOR_OGL_API_C PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex ;
        MOTOR_OGL_API_C PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv ;
        MOTOR_OGL_API_C PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName ;
        MOTOR_OGL_API_C PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding ;

    // gl version 3.2

        MOTOR_OGL_API_C PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex ;
        MOTOR_OGL_API_C PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex ;
        MOTOR_OGL_API_C PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex ;
        MOTOR_OGL_API_C PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex ;
        MOTOR_OGL_API_C PFNGLPROVOKINGVERTEXPROC glProvokingVertex ;
        MOTOR_OGL_API_C PFNGLFENCESYNCPROC glFenceSync ;
        MOTOR_OGL_API_C PFNGLISSYNCPROC glIsSync ;
        MOTOR_OGL_API_C PFNGLDELETESYNCPROC glDeleteSync ;
        MOTOR_OGL_API_C PFNGLCLIENTWAITSYNCPROC glClientWaitSync ;
        MOTOR_OGL_API_C PFNGLWAITSYNCPROC glWaitSync ;
        MOTOR_OGL_API_C PFNGLGETINTEGER64VPROC glGetInteger64v ;
        MOTOR_OGL_API_C PFNGLGETSYNCIVPROC glGetSynciv ;
        MOTOR_OGL_API_C PFNGLGETINTEGER64I_VPROC glGetInteger64i_v ;
        MOTOR_OGL_API_C PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v ;
        MOTOR_OGL_API_C PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture ;
        MOTOR_OGL_API_C PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample ;
        MOTOR_OGL_API_C PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample ;
        MOTOR_OGL_API_C PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv ;
        MOTOR_OGL_API_C PFNGLSAMPLEMASKIPROC glSampleMaski ;

    // gl version 3.3

        MOTOR_OGL_API_C PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed ;
        MOTOR_OGL_API_C PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex ;
        MOTOR_OGL_API_C PFNGLGENSAMPLERSPROC glGenSamplers ;
        MOTOR_OGL_API_C PFNGLDELETESAMPLERSPROC glDeleteSamplers ;
        MOTOR_OGL_API_C PFNGLISSAMPLERPROC glIsSampler ;
        MOTOR_OGL_API_C PFNGLBINDSAMPLERPROC glBindSampler ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv ;
        MOTOR_OGL_API_C PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv ;
        MOTOR_OGL_API_C PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv ;
        MOTOR_OGL_API_C PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv ;
        MOTOR_OGL_API_C PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv ;
        MOTOR_OGL_API_C PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv ;
        MOTOR_OGL_API_C PFNGLQUERYCOUNTERPROC glQueryCounter ;
        MOTOR_OGL_API_C PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v ;
        MOTOR_OGL_API_C PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv ;

    // gl version 4.0

        MOTOR_OGL_API_C PFNGLMINSAMPLESHADINGPROC glMinSampleShading ;
        MOTOR_OGL_API_C PFNGLBLENDEQUATIONIPROC glBlendEquationi ;
        MOTOR_OGL_API_C PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei ;
        MOTOR_OGL_API_C PFNGLBLENDFUNCIPROC glBlendFunci ;
        MOTOR_OGL_API_C PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei ;
        MOTOR_OGL_API_C PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect ;
        MOTOR_OGL_API_C PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect ;
        MOTOR_OGL_API_C PFNGLUNIFORM1DPROC glUniform1d ;
        MOTOR_OGL_API_C PFNGLUNIFORM2DPROC glUniform2d ;
        MOTOR_OGL_API_C PFNGLUNIFORM3DPROC glUniform3d ;
        MOTOR_OGL_API_C PFNGLUNIFORM4DPROC glUniform4d ;
        MOTOR_OGL_API_C PFNGLUNIFORM1DVPROC glUniform1dv ;
        MOTOR_OGL_API_C PFNGLUNIFORM2DVPROC glUniform2dv ;
        MOTOR_OGL_API_C PFNGLUNIFORM3DVPROC glUniform3dv ;
        MOTOR_OGL_API_C PFNGLUNIFORM4DVPROC glUniform4dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv ;
        MOTOR_OGL_API_C PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMDVPROC glGetUniformdv ;
        MOTOR_OGL_API_C PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation ;
        MOTOR_OGL_API_C PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex ;
        MOTOR_OGL_API_C PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv ;
        MOTOR_OGL_API_C PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName ;
        MOTOR_OGL_API_C PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName ;
        MOTOR_OGL_API_C PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv ;
        MOTOR_OGL_API_C PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv ;
        MOTOR_OGL_API_C PFNGLPATCHPARAMETERIPROC glPatchParameteri ;
        MOTOR_OGL_API_C PFNGLPATCHPARAMETERFVPROC glPatchParameterfv ;
        MOTOR_OGL_API_C PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback ;
        MOTOR_OGL_API_C PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks ;
        MOTOR_OGL_API_C PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks ;
        MOTOR_OGL_API_C PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback ;
        MOTOR_OGL_API_C PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback ;
        MOTOR_OGL_API_C PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback ;
        MOTOR_OGL_API_C PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback ;
        MOTOR_OGL_API_C PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream ;
        MOTOR_OGL_API_C PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed ;
        MOTOR_OGL_API_C PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed ;
        MOTOR_OGL_API_C PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv ;

    // gl version 4.1

        MOTOR_OGL_API_C PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler ;
        MOTOR_OGL_API_C PFNGLSHADERBINARYPROC glShaderBinary ;
        MOTOR_OGL_API_C PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat ;
        MOTOR_OGL_API_C PFNGLDEPTHRANGEFPROC glDepthRangef ;
        MOTOR_OGL_API_C PFNGLCLEARDEPTHFPROC glClearDepthf ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMBINARYPROC glGetProgramBinary ;
        MOTOR_OGL_API_C PFNGLPROGRAMBINARYPROC glProgramBinary ;
        MOTOR_OGL_API_C PFNGLPROGRAMPARAMETERIPROC glProgramParameteri ;
        MOTOR_OGL_API_C PFNGLUSEPROGRAMSTAGESPROC  glUseProgramStages ;
        MOTOR_OGL_API_C PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram ;
        MOTOR_OGL_API_C PFNGLCREATESHADERPROGRAMVPROC  glCreateShaderProgramv ;
        MOTOR_OGL_API_C PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline ;
        MOTOR_OGL_API_C PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines ;
        MOTOR_OGL_API_C PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines ;
        MOTOR_OGL_API_C PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1IPROC  glProgramUniform1i ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1IVPROC  glProgramUniform1iv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv ;
        MOTOR_OGL_API_C PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv ;
        MOTOR_OGL_API_C PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline ;
        MOTOR_OGL_API_C PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d  ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv ;
        MOTOR_OGL_API_C PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer ;
        MOTOR_OGL_API_C PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv ;
        MOTOR_OGL_API_C PFNGLVIEWPORTARRAYVPROC glViewportArrayv ;
        MOTOR_OGL_API_C PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf ;
        MOTOR_OGL_API_C PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv ;
        MOTOR_OGL_API_C PFNGLSCISSORARRAYVPROC glScissorArrayv ;
        MOTOR_OGL_API_C PFNGLSCISSORINDEXEDPROC glScissorIndexed ;
        MOTOR_OGL_API_C PFNGLSCISSORINDEXEDVPROC glScissorIndexedv ;
        MOTOR_OGL_API_C PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv ;
        MOTOR_OGL_API_C PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed ;
        MOTOR_OGL_API_C PFNGLGETFLOATI_VPROC glGetFloati_v ;
        MOTOR_OGL_API_C PFNGLGETDOUBLEI_VPROC glGetDoublei_v ;

        #if 0
    }
}
#endif