#pragma once

#include "../result.h"
#include "../api.h"
#include "../typedefs.h"

#if defined( MOTOR_TARGET_OS_WIN )
#include <windows.h>
#elif defined( MOTOR_TARGET_OS_LIN )
#else
#endif

#include <GL/glcorearb.h>
//#define GL_VERSION_1_1 0

#include <list>

namespace motor
{
    namespace ogl
    {
        struct MOTOR_OGL_API gl
        {
            motor_this_typedefs( gl ) ;

        public:

            typedef std::list< char_t const * > string_list_t ;
            static string_list_t _extensions ;

            static void_ptr_t load_gl_function( char_cptr_t name ) ;

            static bool_t _init ;

        public:

            static motor::ogl::result init( void_t ) ;

            static bool_t is_supported( char const* name ) ;
        };
    }
}

namespace motor
{
    namespace ogl
    {
    // gl version 1.0

        MOTOR_OGL_API PFNGLCULLFACEPROC glCullFace ;
        MOTOR_OGL_API PFNGLFRONTFACEPROC glFrontFace ;
        MOTOR_OGL_API PFNGLHINTPROC glHint ;
        MOTOR_OGL_API PFNGLLINEWIDTHPROC glLineWidth;
        MOTOR_OGL_API PFNGLPOINTSIZEPROC glPointSize ;
        MOTOR_OGL_API PFNGLPOLYGONMODEPROC glPolygonMode ;
        MOTOR_OGL_API PFNGLSCISSORPROC glScissor ;
        MOTOR_OGL_API PFNGLTEXPARAMETERFPROC glTexParameterf ;
        MOTOR_OGL_API PFNGLTEXPARAMETERFVPROC glTexParameterfv ;
        MOTOR_OGL_API PFNGLTEXPARAMETERIPROC glTexParameteri ;
        MOTOR_OGL_API PFNGLTEXPARAMETERIVPROC glTexParameteriv ;
        MOTOR_OGL_API PFNGLTEXIMAGE1DPROC glTexImage1D ;
        MOTOR_OGL_API PFNGLTEXIMAGE2DPROC glTexImage2D ;
        MOTOR_OGL_API PFNGLDRAWBUFFERPROC glDrawBuffer ;
        MOTOR_OGL_API PFNGLCLEARPROC glClear ;
        MOTOR_OGL_API PFNGLCLEARCOLORPROC glClearColor ;
        MOTOR_OGL_API PFNGLCLEARSTENCILPROC glClearStencil ;
        MOTOR_OGL_API PFNGLCLEARDEPTHPROC glClearDepth ;
        MOTOR_OGL_API PFNGLSTENCILMASKPROC glStencilMask ;
        MOTOR_OGL_API PFNGLCOLORMASKPROC glColorMask ;
        MOTOR_OGL_API PFNGLDEPTHMASKPROC glDepthMask ;
        MOTOR_OGL_API PFNGLDISABLEPROC glDisable ;
        MOTOR_OGL_API PFNGLENABLEPROC glEnable ;
        MOTOR_OGL_API PFNGLFINISHPROC glFinish ;
        MOTOR_OGL_API PFNGLFLUSHPROC glFlush ;
        MOTOR_OGL_API PFNGLBLENDFUNCPROC glBlendFunc ;
        MOTOR_OGL_API PFNGLLOGICOPPROC glLogicOp ;
        MOTOR_OGL_API PFNGLSTENCILFUNCPROC glStencilFunc ;
        MOTOR_OGL_API PFNGLSTENCILOPPROC glStencilOp ;
        MOTOR_OGL_API PFNGLDEPTHFUNCPROC glDepthFunc ;
        MOTOR_OGL_API PFNGLPIXELSTOREFPROC glPixelStoref ;
        MOTOR_OGL_API PFNGLPIXELSTOREIPROC glPixelStorei ;
        MOTOR_OGL_API PFNGLREADBUFFERPROC glReadBuffer ;
        MOTOR_OGL_API PFNGLREADPIXELSPROC glReadPixels ;
        MOTOR_OGL_API PFNGLGETBOOLEANVPROC glGetBooleanv ;
        MOTOR_OGL_API PFNGLGETDOUBLEVPROC glGetDoublev ;
        MOTOR_OGL_API PFNGLGETERRORPROC glGetError ;
        MOTOR_OGL_API PFNGLGETFLOATVPROC glGetFloatv ;
        MOTOR_OGL_API PFNGLGETINTEGERVPROC glGetIntegerv ;
        MOTOR_OGL_API PFNGLGETSTRINGPROC glGetString ;
        MOTOR_OGL_API PFNGLGETTEXIMAGEPROC glGetTexImage ;
        MOTOR_OGL_API PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv ;
        MOTOR_OGL_API PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv ;
        MOTOR_OGL_API PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv ;
        MOTOR_OGL_API PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv ;
        MOTOR_OGL_API PFNGLISENABLEDPROC glIsEnabled ;
        MOTOR_OGL_API PFNGLDEPTHRANGEPROC glDepthRange ;
        MOTOR_OGL_API PFNGLVIEWPORTPROC glViewport ;

    // gl version 1.1

        MOTOR_OGL_API PFNGLDRAWARRAYSPROC glDrawArrays ;
        MOTOR_OGL_API PFNGLDRAWELEMENTSPROC glDrawElements ;
        MOTOR_OGL_API PFNGLGETPOINTERVPROC glGetPointerv ;
        MOTOR_OGL_API PFNGLPOLYGONOFFSETPROC glPolygonOffset ;
        MOTOR_OGL_API PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D ;
        MOTOR_OGL_API PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D ;
        MOTOR_OGL_API PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D ;
        MOTOR_OGL_API PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D ;
        MOTOR_OGL_API PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D ;
        MOTOR_OGL_API PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D ;
        MOTOR_OGL_API PFNGLBINDTEXTUREPROC glBindTexture ;
        MOTOR_OGL_API PFNGLDELETETEXTURESPROC glDeleteTextures ;
        MOTOR_OGL_API PFNGLGENTEXTURESPROC glGenTextures ;
        MOTOR_OGL_API PFNGLISTEXTUREPROC glIsTexture ;

    // gl version 1.2

        MOTOR_OGL_API PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements ;
        MOTOR_OGL_API PFNGLTEXIMAGE3DPROC glTexImage3D ;
        MOTOR_OGL_API PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D ;
        MOTOR_OGL_API PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D ;

    // gl version 1.3

        MOTOR_OGL_API PFNGLACTIVETEXTUREPROC glActiveTexture ;
        MOTOR_OGL_API PFNGLSAMPLECOVERAGEPROC glSampleCoverage ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D ;
        MOTOR_OGL_API PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D ;
        MOTOR_OGL_API PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage ;

    // gl version 1.4

        MOTOR_OGL_API PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate ;
        MOTOR_OGL_API PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays ;
        MOTOR_OGL_API PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements ;
        MOTOR_OGL_API PFNGLPOINTPARAMETERFPROC glPointParameterf ;
        MOTOR_OGL_API PFNGLPOINTPARAMETERFVPROC glPointParameterfv ;
        MOTOR_OGL_API PFNGLPOINTPARAMETERIPROC glPointParameteri ;
        MOTOR_OGL_API PFNGLPOINTPARAMETERIVPROC glPointParameteriv ;
        MOTOR_OGL_API PFNGLBLENDCOLORPROC glBlendColor ;
        MOTOR_OGL_API PFNGLBLENDEQUATIONPROC glBlendEquation ;

    // gl version 1.5

        MOTOR_OGL_API PFNGLGENQUERIESPROC glGenQueries  ;
        MOTOR_OGL_API PFNGLDELETEQUERIESPROC glDeleteQueries ;
        MOTOR_OGL_API PFNGLISQUERYPROC glIsQuery ;
        MOTOR_OGL_API PFNGLBEGINQUERYPROC glBeginQuery ;
        MOTOR_OGL_API PFNGLENDQUERYPROC glEndQuery ;
        MOTOR_OGL_API PFNGLGETQUERYIVPROC glGetQueryiv ;
        MOTOR_OGL_API PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv ;
        MOTOR_OGL_API PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv ;
        MOTOR_OGL_API PFNGLBINDBUFFERPROC glBindBuffer ;
        MOTOR_OGL_API PFNGLDELETEBUFFERSPROC glDeleteBuffers ;
        MOTOR_OGL_API PFNGLGENBUFFERSPROC glGenBuffers ;
        MOTOR_OGL_API PFNGLISBUFFERPROC glIsBuffer ;
        MOTOR_OGL_API PFNGLBUFFERDATAPROC glBufferData ;
        MOTOR_OGL_API PFNGLBUFFERSUBDATAPROC glBufferSubData ;
        MOTOR_OGL_API PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData ;
        MOTOR_OGL_API PFNGLMAPBUFFERPROC glMapBuffer ;
        MOTOR_OGL_API PFNGLUNMAPBUFFERPROC glUnmapBuffer ;
        MOTOR_OGL_API PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv ;
        MOTOR_OGL_API PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv ;

    // gl version 2.0

        MOTOR_OGL_API PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate  ;
        MOTOR_OGL_API PFNGLDRAWBUFFERSPROC glDrawBuffers ;
        MOTOR_OGL_API PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate ;
        MOTOR_OGL_API PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate ;
        MOTOR_OGL_API PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate ;
        MOTOR_OGL_API PFNGLATTACHSHADERPROC glAttachShader ;
        MOTOR_OGL_API PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation ;
        MOTOR_OGL_API PFNGLCOMPILESHADERPROC glCompileShader ;
        MOTOR_OGL_API PFNGLCREATEPROGRAMPROC glCreateProgram ;
        MOTOR_OGL_API PFNGLCREATESHADERPROC glCreateShader ;
        MOTOR_OGL_API PFNGLDELETEPROGRAMPROC glDeleteProgram ;
        MOTOR_OGL_API PFNGLDELETESHADERPROC glDeleteShader ;
        MOTOR_OGL_API PFNGLDETACHSHADERPROC glDetachShader ;
        MOTOR_OGL_API PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray ;
        MOTOR_OGL_API PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray ;
        MOTOR_OGL_API PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib ;
        MOTOR_OGL_API PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform ;
        MOTOR_OGL_API PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders ;
        MOTOR_OGL_API PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation ;
        MOTOR_OGL_API PFNGLGETPROGRAMIVPROC glGetProgramiv ;
        MOTOR_OGL_API PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog ;
        MOTOR_OGL_API PFNGLGETSHADERIVPROC glGetShaderiv ;
        MOTOR_OGL_API PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog ;
        MOTOR_OGL_API PFNGLGETSHADERSOURCEPROC glGetShaderSource ;
        MOTOR_OGL_API PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation ;
        MOTOR_OGL_API PFNGLGETUNIFORMFVPROC glGetUniformfv ;
        MOTOR_OGL_API PFNGLGETUNIFORMIVPROC glGetUniformiv ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv ;
        MOTOR_OGL_API PFNGLISPROGRAMPROC glIsProgram ;
        MOTOR_OGL_API PFNGLISSHADERPROC glIsShader ;
        MOTOR_OGL_API PFNGLLINKPROGRAMPROC glLinkProgram ;
        MOTOR_OGL_API PFNGLSHADERSOURCEPROC glShaderSource ;
        MOTOR_OGL_API PFNGLUSEPROGRAMPROC glUseProgram ;
        MOTOR_OGL_API PFNGLUNIFORM1FPROC glUniform1f ;
        MOTOR_OGL_API PFNGLUNIFORM2FPROC glUniform2f ;
        MOTOR_OGL_API PFNGLUNIFORM3FPROC glUniform3f ;
        MOTOR_OGL_API PFNGLUNIFORM4FPROC glUniform4f ;
        MOTOR_OGL_API PFNGLUNIFORM1IPROC glUniform1i ;
        MOTOR_OGL_API PFNGLUNIFORM2IPROC glUniform2i ;
        MOTOR_OGL_API PFNGLUNIFORM3IPROC glUniform3i ;
        MOTOR_OGL_API PFNGLUNIFORM4IPROC glUniform4i ;
        MOTOR_OGL_API PFNGLUNIFORM1FVPROC glUniform1fv ;
        MOTOR_OGL_API PFNGLUNIFORM2FVPROC glUniform2fv ;
        MOTOR_OGL_API PFNGLUNIFORM3FVPROC glUniform3fv ;
        MOTOR_OGL_API PFNGLUNIFORM4FVPROC glUniform4fv ;
        MOTOR_OGL_API PFNGLUNIFORM1IVPROC glUniform1iv ;
        MOTOR_OGL_API PFNGLUNIFORM2IVPROC glUniform2iv ;
        MOTOR_OGL_API PFNGLUNIFORM3IVPROC glUniform3iv ;
        MOTOR_OGL_API PFNGLUNIFORM4IVPROC glUniform4iv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv ;
        MOTOR_OGL_API PFNGLVALIDATEPROGRAMPROC glValidateProgram ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer ;

    // gl version 2.1

        MOTOR_OGL_API PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv ;

    // gl version 3.0

        MOTOR_OGL_API PFNGLCOLORMASKIPROC glColorMaski ;
        MOTOR_OGL_API PFNGLGETBOOLEANI_VPROC glGetBooleani_v ;
        MOTOR_OGL_API PFNGLGETINTEGERI_VPROC glGetIntegeri_v ;
        MOTOR_OGL_API PFNGLENABLEIPROC glEnablei ;
        MOTOR_OGL_API PFNGLDISABLEIPROC glDisablei ;
        MOTOR_OGL_API PFNGLISENABLEDIPROC glIsEnabledi ;
        MOTOR_OGL_API PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback ;
        MOTOR_OGL_API PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback ;
        MOTOR_OGL_API PFNGLBINDBUFFERRANGEPROC glBindBufferRange ;
        MOTOR_OGL_API PFNGLBINDBUFFERBASEPROC glBindBufferBase ;
        MOTOR_OGL_API PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings ;
        MOTOR_OGL_API PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying ;
        MOTOR_OGL_API PFNGLCLAMPCOLORPROC glClampColor ;
        MOTOR_OGL_API PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender ;
        MOTOR_OGL_API PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4SVPROC  glVertexAttribI4sv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv ;
        MOTOR_OGL_API PFNGLGETUNIFORMUIVPROC glGetUniformuiv ;
        MOTOR_OGL_API PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation ;
        MOTOR_OGL_API PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation ;
        MOTOR_OGL_API PFNGLUNIFORM1UIPROC glUniform1ui ;
        MOTOR_OGL_API PFNGLUNIFORM2UIPROC glUniform2ui ;
        MOTOR_OGL_API PFNGLUNIFORM3UIPROC glUniform3ui ;
        MOTOR_OGL_API PFNGLUNIFORM4UIPROC glUniform4ui ;
        MOTOR_OGL_API PFNGLUNIFORM1UIVPROC glUniform1uiv ;
        MOTOR_OGL_API PFNGLUNIFORM2UIVPROC glUniform2uiv ;
        MOTOR_OGL_API PFNGLUNIFORM3UIVPROC glUniform3uiv ;
        MOTOR_OGL_API PFNGLUNIFORM4UIVPROC glUniform4uiv ;
        MOTOR_OGL_API PFNGLTEXPARAMETERIIVPROC glTexParameterIiv ;
        MOTOR_OGL_API PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv ;
        MOTOR_OGL_API PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv ;
        MOTOR_OGL_API PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv ;
        MOTOR_OGL_API PFNGLCLEARBUFFERIVPROC glClearBufferiv ;
        MOTOR_OGL_API PFNGLCLEARBUFFERUIVPROC glClearBufferuiv ;
        MOTOR_OGL_API PFNGLCLEARBUFFERFVPROC glClearBufferfv ;
        MOTOR_OGL_API PFNGLCLEARBUFFERFIPROC glClearBufferfi ;
        MOTOR_OGL_API PFNGLGETSTRINGIPROC glGetStringi ;
        MOTOR_OGL_API PFNGLISRENDERBUFFERPROC glIsRenderbuffer ;
        MOTOR_OGL_API PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer ;
        MOTOR_OGL_API PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers ;
        MOTOR_OGL_API PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers ;
        MOTOR_OGL_API PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage ;
        MOTOR_OGL_API PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv ;
        MOTOR_OGL_API PFNGLISFRAMEBUFFERPROC glIsFramebuffer ;
        MOTOR_OGL_API PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer ;
        MOTOR_OGL_API PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers ;
        MOTOR_OGL_API PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers ;
        MOTOR_OGL_API PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer ;
        MOTOR_OGL_API PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv ;
        MOTOR_OGL_API PFNGLGENERATEMIPMAPPROC glGenerateMipmap ;
        MOTOR_OGL_API PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer ;
        MOTOR_OGL_API PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer ;
        MOTOR_OGL_API PFNGLMAPBUFFERRANGEPROC glMapBufferRange ;
        MOTOR_OGL_API PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange ;
        MOTOR_OGL_API PFNGLBINDVERTEXARRAYPROC glBindVertexArray ;
        MOTOR_OGL_API PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays ;
        MOTOR_OGL_API PFNGLGENVERTEXARRAYSPROC glGenVertexArrays ;
        MOTOR_OGL_API PFNGLISVERTEXARRAYPROC glIsVertexArray ;

    // gl version 3.1

        MOTOR_OGL_API PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced ;
        MOTOR_OGL_API PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced ;
        MOTOR_OGL_API PFNGLTEXBUFFERPROC glTexBuffer ;
        MOTOR_OGL_API PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex ;
        MOTOR_OGL_API PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData ;
        MOTOR_OGL_API PFNGLGETUNIFORMINDICESPROC glGetUniformIndices ;
        MOTOR_OGL_API PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv ;
        MOTOR_OGL_API PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName ;
        MOTOR_OGL_API PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex ;
        MOTOR_OGL_API PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv ;
        MOTOR_OGL_API PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName ;
        MOTOR_OGL_API PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding ;

    // gl version 3.2

        MOTOR_OGL_API PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex ;
        MOTOR_OGL_API PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex ;
        MOTOR_OGL_API PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex ;
        MOTOR_OGL_API PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex ;
        MOTOR_OGL_API PFNGLPROVOKINGVERTEXPROC glProvokingVertex ;
        MOTOR_OGL_API PFNGLFENCESYNCPROC glFenceSync ;
        MOTOR_OGL_API PFNGLISSYNCPROC glIsSync ;
        MOTOR_OGL_API PFNGLDELETESYNCPROC glDeleteSync ;
        MOTOR_OGL_API PFNGLCLIENTWAITSYNCPROC glClientWaitSync ;
        MOTOR_OGL_API PFNGLWAITSYNCPROC glWaitSync ;
        MOTOR_OGL_API PFNGLGETINTEGER64VPROC glGetInteger64v ;
        MOTOR_OGL_API PFNGLGETSYNCIVPROC glGetSynciv ;
        MOTOR_OGL_API PFNGLGETINTEGER64I_VPROC glGetInteger64i_v ;
        MOTOR_OGL_API PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v ;
        MOTOR_OGL_API PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture ;
        MOTOR_OGL_API PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample ;
        MOTOR_OGL_API PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample ;
        MOTOR_OGL_API PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv ;
        MOTOR_OGL_API PFNGLSAMPLEMASKIPROC glSampleMaski ;

    // gl version 3.3

        MOTOR_OGL_API PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed ;
        MOTOR_OGL_API PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex ;
        MOTOR_OGL_API PFNGLGENSAMPLERSPROC glGenSamplers ;
        MOTOR_OGL_API PFNGLDELETESAMPLERSPROC glDeleteSamplers ;
        MOTOR_OGL_API PFNGLISSAMPLERPROC glIsSampler ;
        MOTOR_OGL_API PFNGLBINDSAMPLERPROC glBindSampler ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv ;
        MOTOR_OGL_API PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv ;
        MOTOR_OGL_API PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv ;
        MOTOR_OGL_API PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv ;
        MOTOR_OGL_API PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv ;
        MOTOR_OGL_API PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv ;
        MOTOR_OGL_API PFNGLQUERYCOUNTERPROC glQueryCounter ;
        MOTOR_OGL_API PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v ;
        MOTOR_OGL_API PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv ;

    // gl version 4.0

        MOTOR_OGL_API PFNGLMINSAMPLESHADINGPROC glMinSampleShading ;
        MOTOR_OGL_API PFNGLBLENDEQUATIONIPROC glBlendEquationi ;
        MOTOR_OGL_API PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei ;
        MOTOR_OGL_API PFNGLBLENDFUNCIPROC glBlendFunci ;
        MOTOR_OGL_API PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei ;
        MOTOR_OGL_API PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect ;
        MOTOR_OGL_API PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect ;
        MOTOR_OGL_API PFNGLUNIFORM1DPROC glUniform1d ;
        MOTOR_OGL_API PFNGLUNIFORM2DPROC glUniform2d ;
        MOTOR_OGL_API PFNGLUNIFORM3DPROC glUniform3d ;
        MOTOR_OGL_API PFNGLUNIFORM4DPROC glUniform4d ;
        MOTOR_OGL_API PFNGLUNIFORM1DVPROC glUniform1dv ;
        MOTOR_OGL_API PFNGLUNIFORM2DVPROC glUniform2dv ;
        MOTOR_OGL_API PFNGLUNIFORM3DVPROC glUniform3dv ;
        MOTOR_OGL_API PFNGLUNIFORM4DVPROC glUniform4dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv ;
        MOTOR_OGL_API PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv ;
        MOTOR_OGL_API PFNGLGETUNIFORMDVPROC glGetUniformdv ;
        MOTOR_OGL_API PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation ;
        MOTOR_OGL_API PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex ;
        MOTOR_OGL_API PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv ;
        MOTOR_OGL_API PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName ;
        MOTOR_OGL_API PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName ;
        MOTOR_OGL_API PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv ;
        MOTOR_OGL_API PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv ;
        MOTOR_OGL_API PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv ;
        MOTOR_OGL_API PFNGLPATCHPARAMETERIPROC glPatchParameteri ;
        MOTOR_OGL_API PFNGLPATCHPARAMETERFVPROC glPatchParameterfv ;
        MOTOR_OGL_API PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback ;
        MOTOR_OGL_API PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks ;
        MOTOR_OGL_API PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks ;
        MOTOR_OGL_API PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback ;
        MOTOR_OGL_API PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback ;
        MOTOR_OGL_API PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback ;
        MOTOR_OGL_API PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback ;
        MOTOR_OGL_API PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream ;
        MOTOR_OGL_API PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed ;
        MOTOR_OGL_API PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed ;
        MOTOR_OGL_API PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv ;

    // gl version 4.1

        MOTOR_OGL_API PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler ;
        MOTOR_OGL_API PFNGLSHADERBINARYPROC glShaderBinary ;
        MOTOR_OGL_API PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat ;
        MOTOR_OGL_API PFNGLDEPTHRANGEFPROC glDepthRangef ;
        MOTOR_OGL_API PFNGLCLEARDEPTHFPROC glClearDepthf ;
        MOTOR_OGL_API PFNGLGETPROGRAMBINARYPROC glGetProgramBinary ;
        MOTOR_OGL_API PFNGLPROGRAMBINARYPROC glProgramBinary ;
        MOTOR_OGL_API PFNGLPROGRAMPARAMETERIPROC glProgramParameteri ;
        MOTOR_OGL_API PFNGLUSEPROGRAMSTAGESPROC  glUseProgramStages ;
        MOTOR_OGL_API PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram ;
        MOTOR_OGL_API PFNGLCREATESHADERPROGRAMVPROC  glCreateShaderProgramv ;
        MOTOR_OGL_API PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline ;
        MOTOR_OGL_API PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines ;
        MOTOR_OGL_API PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines ;
        MOTOR_OGL_API PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline ;
        MOTOR_OGL_API PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1IPROC  glProgramUniform1i ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1IVPROC  glProgramUniform1iv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv ;
        MOTOR_OGL_API PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv ;
        MOTOR_OGL_API PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline ;
        MOTOR_OGL_API PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d  ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv ;
        MOTOR_OGL_API PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer ;
        MOTOR_OGL_API PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv ;
        MOTOR_OGL_API PFNGLVIEWPORTARRAYVPROC glViewportArrayv ;
        MOTOR_OGL_API PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf ;
        MOTOR_OGL_API PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv ;
        MOTOR_OGL_API PFNGLSCISSORARRAYVPROC glScissorArrayv ;
        MOTOR_OGL_API PFNGLSCISSORINDEXEDPROC glScissorIndexed ;
        MOTOR_OGL_API PFNGLSCISSORINDEXEDVPROC glScissorIndexedv ;
        MOTOR_OGL_API PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv ;
        MOTOR_OGL_API PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed ;
        MOTOR_OGL_API PFNGLGETFLOATI_VPROC glGetFloati_v ;
        MOTOR_OGL_API PFNGLGETDOUBLEI_VPROC glGetDoublei_v ;
    }
}
