#pragma once

#include "../result.h"
#include "../api.h"
#include "../typedefs.h"

#if defined( MOTOR_TARGET_OS_WIN )
#include <windows.h>
#elif defined( MOTOR_TARGET_OS_LIN )
#else
#endif

#include <GL/glcorearb.h>
//#define GL_VERSION_1_1 0

#include <list>

namespace motor
{
    namespace ogl
    {
        struct MOTOR_OGL_API gl
        {
            motor_this_typedefs( gl ) ;

        public:

            typedef std::list< char_t const * > string_list_t ;
            static string_list_t _extensions ;            

            static bool_t _init ;

        public:

            static motor::ogl::result init( void_t ) ;

            static bool_t is_supported( char const* name ) ;
        };
    }
}

#if 0
namespace motor
{
    namespace ogl
    {
        #endif
    // gl version 1.0

        MOTOR_OGL_API_CXX PFNGLCULLFACEPROC glCullFace ;
        MOTOR_OGL_API_CXX PFNGLFRONTFACEPROC glFrontFace ;
        MOTOR_OGL_API_CXX PFNGLHINTPROC glHint ;
        MOTOR_OGL_API_CXX PFNGLLINEWIDTHPROC glLineWidth;
        MOTOR_OGL_API_CXX PFNGLPOINTSIZEPROC glPointSize ;
        MOTOR_OGL_API_CXX PFNGLPOLYGONMODEPROC glPolygonMode ;
        MOTOR_OGL_API_CXX PFNGLSCISSORPROC glScissor ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERFPROC glTexParameterf ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERFVPROC glTexParameterfv ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERIPROC glTexParameteri ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERIVPROC glTexParameteriv ;
        MOTOR_OGL_API_CXX PFNGLTEXIMAGE1DPROC glTexImage1D ;
        MOTOR_OGL_API_CXX PFNGLTEXIMAGE2DPROC glTexImage2D ;
        MOTOR_OGL_API_CXX PFNGLDRAWBUFFERPROC glDrawBuffer ;
        MOTOR_OGL_API_CXX PFNGLCLEARPROC glClear ;
        MOTOR_OGL_API_CXX PFNGLCLEARCOLORPROC glClearColor ;
        MOTOR_OGL_API_CXX PFNGLCLEARSTENCILPROC glClearStencil ;
        MOTOR_OGL_API_CXX PFNGLCLEARDEPTHPROC glClearDepth ;
        MOTOR_OGL_API_CXX PFNGLSTENCILMASKPROC glStencilMask ;
        MOTOR_OGL_API_CXX PFNGLCOLORMASKPROC glColorMask ;
        MOTOR_OGL_API_CXX PFNGLDEPTHMASKPROC glDepthMask ;
        MOTOR_OGL_API_CXX PFNGLDISABLEPROC glDisable ;
        MOTOR_OGL_API_CXX PFNGLENABLEPROC glEnable ;
        MOTOR_OGL_API_CXX PFNGLFINISHPROC glFinish ;
        MOTOR_OGL_API_CXX PFNGLFLUSHPROC glFlush ;
        MOTOR_OGL_API_CXX PFNGLBLENDFUNCPROC glBlendFunc ;
        MOTOR_OGL_API_CXX PFNGLLOGICOPPROC glLogicOp ;
        MOTOR_OGL_API_CXX PFNGLSTENCILFUNCPROC glStencilFunc ;
        MOTOR_OGL_API_CXX PFNGLSTENCILOPPROC glStencilOp ;
        MOTOR_OGL_API_CXX PFNGLDEPTHFUNCPROC glDepthFunc ;
        MOTOR_OGL_API_CXX PFNGLPIXELSTOREFPROC glPixelStoref ;
        MOTOR_OGL_API_CXX PFNGLPIXELSTOREIPROC glPixelStorei ;
        MOTOR_OGL_API_CXX PFNGLREADBUFFERPROC glReadBuffer ;
        MOTOR_OGL_API_CXX PFNGLREADPIXELSPROC glReadPixels ;
        MOTOR_OGL_API_CXX PFNGLGETBOOLEANVPROC glGetBooleanv ;
        MOTOR_OGL_API_CXX PFNGLGETDOUBLEVPROC glGetDoublev ;
        MOTOR_OGL_API_CXX PFNGLGETERRORPROC glGetError ;
        MOTOR_OGL_API_CXX PFNGLGETFLOATVPROC glGetFloatv ;
        MOTOR_OGL_API_CXX PFNGLGETINTEGERVPROC glGetIntegerv ;
        MOTOR_OGL_API_CXX PFNGLGETSTRINGPROC glGetString ;
        MOTOR_OGL_API_CXX PFNGLGETTEXIMAGEPROC glGetTexImage ;
        MOTOR_OGL_API_CXX PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv ;
        MOTOR_OGL_API_CXX PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv ;
        MOTOR_OGL_API_CXX PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv ;
        MOTOR_OGL_API_CXX PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv ;
        MOTOR_OGL_API_CXX PFNGLISENABLEDPROC glIsEnabled ;
        MOTOR_OGL_API_CXX PFNGLDEPTHRANGEPROC glDepthRange ;
        MOTOR_OGL_API_CXX PFNGLVIEWPORTPROC glViewport ;

    // gl version 1.1

        MOTOR_OGL_API_CXX PFNGLDRAWARRAYSPROC glDrawArrays ;
        MOTOR_OGL_API_CXX PFNGLDRAWELEMENTSPROC glDrawElements ;
        MOTOR_OGL_API_CXX PFNGLGETPOINTERVPROC glGetPointerv ;
        MOTOR_OGL_API_CXX PFNGLPOLYGONOFFSETPROC glPolygonOffset ;
        MOTOR_OGL_API_CXX PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D ;
        MOTOR_OGL_API_CXX PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D ;
        MOTOR_OGL_API_CXX PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D ;
        MOTOR_OGL_API_CXX PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D ;
        MOTOR_OGL_API_CXX PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D ;
        MOTOR_OGL_API_CXX PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D ;
        MOTOR_OGL_API_CXX PFNGLBINDTEXTUREPROC glBindTexture ;
        MOTOR_OGL_API_CXX PFNGLDELETETEXTURESPROC glDeleteTextures ;
        MOTOR_OGL_API_CXX PFNGLGENTEXTURESPROC glGenTextures ;
        MOTOR_OGL_API_CXX PFNGLISTEXTUREPROC glIsTexture ;

    // gl version 1.2

        MOTOR_OGL_API_CXX PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements ;
        MOTOR_OGL_API_CXX PFNGLTEXIMAGE3DPROC glTexImage3D ;
        MOTOR_OGL_API_CXX PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D ;
        MOTOR_OGL_API_CXX PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D ;

    // gl version 1.3

        MOTOR_OGL_API_CXX PFNGLACTIVETEXTUREPROC glActiveTexture ;
        MOTOR_OGL_API_CXX PFNGLSAMPLECOVERAGEPROC glSampleCoverage ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D ;
        MOTOR_OGL_API_CXX PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D ;
        MOTOR_OGL_API_CXX PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage ;

    // gl version 1.4

        MOTOR_OGL_API_CXX PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate ;
        MOTOR_OGL_API_CXX PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays ;
        MOTOR_OGL_API_CXX PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements ;
        MOTOR_OGL_API_CXX PFNGLPOINTPARAMETERFPROC glPointParameterf ;
        MOTOR_OGL_API_CXX PFNGLPOINTPARAMETERFVPROC glPointParameterfv ;
        MOTOR_OGL_API_CXX PFNGLPOINTPARAMETERIPROC glPointParameteri ;
        MOTOR_OGL_API_CXX PFNGLPOINTPARAMETERIVPROC glPointParameteriv ;
        MOTOR_OGL_API_CXX PFNGLBLENDCOLORPROC glBlendColor ;
        MOTOR_OGL_API_CXX PFNGLBLENDEQUATIONPROC glBlendEquation ;

    // gl version 1.5

        MOTOR_OGL_API_CXX PFNGLGENQUERIESPROC glGenQueries  ;
        MOTOR_OGL_API_CXX PFNGLDELETEQUERIESPROC glDeleteQueries ;
        MOTOR_OGL_API_CXX PFNGLISQUERYPROC glIsQuery ;
        MOTOR_OGL_API_CXX PFNGLBEGINQUERYPROC glBeginQuery ;
        MOTOR_OGL_API_CXX PFNGLENDQUERYPROC glEndQuery ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYIVPROC glGetQueryiv ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv ;
        MOTOR_OGL_API_CXX PFNGLBINDBUFFERPROC glBindBuffer ;
        MOTOR_OGL_API_CXX PFNGLDELETEBUFFERSPROC glDeleteBuffers ;
        MOTOR_OGL_API_CXX PFNGLGENBUFFERSPROC glGenBuffers ;
        MOTOR_OGL_API_CXX PFNGLISBUFFERPROC glIsBuffer ;
        MOTOR_OGL_API_CXX PFNGLBUFFERDATAPROC glBufferData ;
        MOTOR_OGL_API_CXX PFNGLBUFFERSUBDATAPROC glBufferSubData ;
        MOTOR_OGL_API_CXX PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData ;
        MOTOR_OGL_API_CXX PFNGLMAPBUFFERPROC glMapBuffer ;
        MOTOR_OGL_API_CXX PFNGLUNMAPBUFFERPROC glUnmapBuffer ;
        MOTOR_OGL_API_CXX PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv ;
        MOTOR_OGL_API_CXX PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv ;

    // gl version 2.0

        MOTOR_OGL_API_CXX PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate  ;
        MOTOR_OGL_API_CXX PFNGLDRAWBUFFERSPROC glDrawBuffers ;
        MOTOR_OGL_API_CXX PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate ;
        MOTOR_OGL_API_CXX PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate ;
        MOTOR_OGL_API_CXX PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate ;
        MOTOR_OGL_API_CXX PFNGLATTACHSHADERPROC glAttachShader ;
        MOTOR_OGL_API_CXX PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation ;
        MOTOR_OGL_API_CXX PFNGLCOMPILESHADERPROC glCompileShader ;
        MOTOR_OGL_API_CXX PFNGLCREATEPROGRAMPROC glCreateProgram ;
        MOTOR_OGL_API_CXX PFNGLCREATESHADERPROC glCreateShader ;
        MOTOR_OGL_API_CXX PFNGLDELETEPROGRAMPROC glDeleteProgram ;
        MOTOR_OGL_API_CXX PFNGLDELETESHADERPROC glDeleteShader ;
        MOTOR_OGL_API_CXX PFNGLDETACHSHADERPROC glDetachShader ;
        MOTOR_OGL_API_CXX PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray ;
        MOTOR_OGL_API_CXX PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform ;
        MOTOR_OGL_API_CXX PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders ;
        MOTOR_OGL_API_CXX PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMIVPROC glGetProgramiv ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog ;
        MOTOR_OGL_API_CXX PFNGLGETSHADERIVPROC glGetShaderiv ;
        MOTOR_OGL_API_CXX PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog ;
        MOTOR_OGL_API_CXX PFNGLGETSHADERSOURCEPROC glGetShaderSource ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMFVPROC glGetUniformfv ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMIVPROC glGetUniformiv ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv ;
        MOTOR_OGL_API_CXX PFNGLISPROGRAMPROC glIsProgram ;
        MOTOR_OGL_API_CXX PFNGLISSHADERPROC glIsShader ;
        MOTOR_OGL_API_CXX PFNGLLINKPROGRAMPROC glLinkProgram ;
        MOTOR_OGL_API_CXX PFNGLSHADERSOURCEPROC glShaderSource ;
        MOTOR_OGL_API_CXX PFNGLUSEPROGRAMPROC glUseProgram ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1FPROC glUniform1f ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2FPROC glUniform2f ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3FPROC glUniform3f ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4FPROC glUniform4f ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1IPROC glUniform1i ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2IPROC glUniform2i ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3IPROC glUniform3i ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4IPROC glUniform4i ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1FVPROC glUniform1fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2FVPROC glUniform2fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3FVPROC glUniform3fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4FVPROC glUniform4fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1IVPROC glUniform1iv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2IVPROC glUniform2iv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3IVPROC glUniform3iv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4IVPROC glUniform4iv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv ;
        MOTOR_OGL_API_CXX PFNGLVALIDATEPROGRAMPROC glValidateProgram ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer ;

    // gl version 2.1

        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv ;

    // gl version 3.0

        MOTOR_OGL_API_CXX PFNGLCOLORMASKIPROC glColorMaski ;
        MOTOR_OGL_API_CXX PFNGLGETBOOLEANI_VPROC glGetBooleani_v ;
        MOTOR_OGL_API_CXX PFNGLGETINTEGERI_VPROC glGetIntegeri_v ;
        MOTOR_OGL_API_CXX PFNGLENABLEIPROC glEnablei ;
        MOTOR_OGL_API_CXX PFNGLDISABLEIPROC glDisablei ;
        MOTOR_OGL_API_CXX PFNGLISENABLEDIPROC glIsEnabledi ;
        MOTOR_OGL_API_CXX PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLBINDBUFFERRANGEPROC glBindBufferRange ;
        MOTOR_OGL_API_CXX PFNGLBINDBUFFERBASEPROC glBindBufferBase ;
        MOTOR_OGL_API_CXX PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings ;
        MOTOR_OGL_API_CXX PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying ;
        MOTOR_OGL_API_CXX PFNGLCLAMPCOLORPROC glClampColor ;
        MOTOR_OGL_API_CXX PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender ;
        MOTOR_OGL_API_CXX PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4SVPROC  glVertexAttribI4sv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMUIVPROC glGetUniformuiv ;
        MOTOR_OGL_API_CXX PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation ;
        MOTOR_OGL_API_CXX PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1UIPROC glUniform1ui ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2UIPROC glUniform2ui ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3UIPROC glUniform3ui ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4UIPROC glUniform4ui ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1UIVPROC glUniform1uiv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2UIVPROC glUniform2uiv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3UIVPROC glUniform3uiv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4UIVPROC glUniform4uiv ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERIIVPROC glTexParameterIiv ;
        MOTOR_OGL_API_CXX PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv ;
        MOTOR_OGL_API_CXX PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv ;
        MOTOR_OGL_API_CXX PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv ;
        MOTOR_OGL_API_CXX PFNGLCLEARBUFFERIVPROC glClearBufferiv ;
        MOTOR_OGL_API_CXX PFNGLCLEARBUFFERUIVPROC glClearBufferuiv ;
        MOTOR_OGL_API_CXX PFNGLCLEARBUFFERFVPROC glClearBufferfv ;
        MOTOR_OGL_API_CXX PFNGLCLEARBUFFERFIPROC glClearBufferfi ;
        MOTOR_OGL_API_CXX PFNGLGETSTRINGIPROC glGetStringi ;
        MOTOR_OGL_API_CXX PFNGLISRENDERBUFFERPROC glIsRenderbuffer ;
        MOTOR_OGL_API_CXX PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer ;
        MOTOR_OGL_API_CXX PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers ;
        MOTOR_OGL_API_CXX PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers ;
        MOTOR_OGL_API_CXX PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage ;
        MOTOR_OGL_API_CXX PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv ;
        MOTOR_OGL_API_CXX PFNGLISFRAMEBUFFERPROC glIsFramebuffer ;
        MOTOR_OGL_API_CXX PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer ;
        MOTOR_OGL_API_CXX PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers ;
        MOTOR_OGL_API_CXX PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers ;
        MOTOR_OGL_API_CXX PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer ;
        MOTOR_OGL_API_CXX PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv ;
        MOTOR_OGL_API_CXX PFNGLGENERATEMIPMAPPROC glGenerateMipmap ;
        MOTOR_OGL_API_CXX PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer ;
        MOTOR_OGL_API_CXX PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer ;
        MOTOR_OGL_API_CXX PFNGLMAPBUFFERRANGEPROC glMapBufferRange ;
        MOTOR_OGL_API_CXX PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange ;
        MOTOR_OGL_API_CXX PFNGLBINDVERTEXARRAYPROC glBindVertexArray ;
        MOTOR_OGL_API_CXX PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays ;
        MOTOR_OGL_API_CXX PFNGLGENVERTEXARRAYSPROC glGenVertexArrays ;
        MOTOR_OGL_API_CXX PFNGLISVERTEXARRAYPROC glIsVertexArray ;

    // gl version 3.1

        MOTOR_OGL_API_CXX PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced ;
        MOTOR_OGL_API_CXX PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced ;
        MOTOR_OGL_API_CXX PFNGLTEXBUFFERPROC glTexBuffer ;
        MOTOR_OGL_API_CXX PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex ;
        MOTOR_OGL_API_CXX PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMINDICESPROC glGetUniformIndices ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding ;

    // gl version 3.2

        MOTOR_OGL_API_CXX PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex ;
        MOTOR_OGL_API_CXX PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex ;
        MOTOR_OGL_API_CXX PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex ;
        MOTOR_OGL_API_CXX PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex ;
        MOTOR_OGL_API_CXX PFNGLPROVOKINGVERTEXPROC glProvokingVertex ;
        MOTOR_OGL_API_CXX PFNGLFENCESYNCPROC glFenceSync ;
        MOTOR_OGL_API_CXX PFNGLISSYNCPROC glIsSync ;
        MOTOR_OGL_API_CXX PFNGLDELETESYNCPROC glDeleteSync ;
        MOTOR_OGL_API_CXX PFNGLCLIENTWAITSYNCPROC glClientWaitSync ;
        MOTOR_OGL_API_CXX PFNGLWAITSYNCPROC glWaitSync ;
        MOTOR_OGL_API_CXX PFNGLGETINTEGER64VPROC glGetInteger64v ;
        MOTOR_OGL_API_CXX PFNGLGETSYNCIVPROC glGetSynciv ;
        MOTOR_OGL_API_CXX PFNGLGETINTEGER64I_VPROC glGetInteger64i_v ;
        MOTOR_OGL_API_CXX PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v ;
        MOTOR_OGL_API_CXX PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture ;
        MOTOR_OGL_API_CXX PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample ;
        MOTOR_OGL_API_CXX PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample ;
        MOTOR_OGL_API_CXX PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv ;
        MOTOR_OGL_API_CXX PFNGLSAMPLEMASKIPROC glSampleMaski ;

    // gl version 3.3

        MOTOR_OGL_API_CXX PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed ;
        MOTOR_OGL_API_CXX PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex ;
        MOTOR_OGL_API_CXX PFNGLGENSAMPLERSPROC glGenSamplers ;
        MOTOR_OGL_API_CXX PFNGLDELETESAMPLERSPROC glDeleteSamplers ;
        MOTOR_OGL_API_CXX PFNGLISSAMPLERPROC glIsSampler ;
        MOTOR_OGL_API_CXX PFNGLBINDSAMPLERPROC glBindSampler ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv ;
        MOTOR_OGL_API_CXX PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv ;
        MOTOR_OGL_API_CXX PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv ;
        MOTOR_OGL_API_CXX PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv ;
        MOTOR_OGL_API_CXX PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv ;
        MOTOR_OGL_API_CXX PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv ;
        MOTOR_OGL_API_CXX PFNGLQUERYCOUNTERPROC glQueryCounter ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv ;

    // gl version 4.0

        MOTOR_OGL_API_CXX PFNGLMINSAMPLESHADINGPROC glMinSampleShading ;
        MOTOR_OGL_API_CXX PFNGLBLENDEQUATIONIPROC glBlendEquationi ;
        MOTOR_OGL_API_CXX PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei ;
        MOTOR_OGL_API_CXX PFNGLBLENDFUNCIPROC glBlendFunci ;
        MOTOR_OGL_API_CXX PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei ;
        MOTOR_OGL_API_CXX PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect ;
        MOTOR_OGL_API_CXX PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1DPROC glUniform1d ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2DPROC glUniform2d ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3DPROC glUniform3d ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4DPROC glUniform4d ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM1DVPROC glUniform1dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM2DVPROC glUniform2dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM3DVPROC glUniform3dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORM4DVPROC glUniform4dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMDVPROC glGetUniformdv ;
        MOTOR_OGL_API_CXX PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation ;
        MOTOR_OGL_API_CXX PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName ;
        MOTOR_OGL_API_CXX PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName ;
        MOTOR_OGL_API_CXX PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv ;
        MOTOR_OGL_API_CXX PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv ;
        MOTOR_OGL_API_CXX PFNGLPATCHPARAMETERIPROC glPatchParameteri ;
        MOTOR_OGL_API_CXX PFNGLPATCHPARAMETERFVPROC glPatchParameterfv ;
        MOTOR_OGL_API_CXX PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks ;
        MOTOR_OGL_API_CXX PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks ;
        MOTOR_OGL_API_CXX PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback ;
        MOTOR_OGL_API_CXX PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream ;
        MOTOR_OGL_API_CXX PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed ;
        MOTOR_OGL_API_CXX PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed ;
        MOTOR_OGL_API_CXX PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv ;

    // gl version 4.1

        MOTOR_OGL_API_CXX PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler ;
        MOTOR_OGL_API_CXX PFNGLSHADERBINARYPROC glShaderBinary ;
        MOTOR_OGL_API_CXX PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat ;
        MOTOR_OGL_API_CXX PFNGLDEPTHRANGEFPROC glDepthRangef ;
        MOTOR_OGL_API_CXX PFNGLCLEARDEPTHFPROC glClearDepthf ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMBINARYPROC glGetProgramBinary ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMBINARYPROC glProgramBinary ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMPARAMETERIPROC glProgramParameteri ;
        MOTOR_OGL_API_CXX PFNGLUSEPROGRAMSTAGESPROC  glUseProgramStages ;
        MOTOR_OGL_API_CXX PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram ;
        MOTOR_OGL_API_CXX PFNGLCREATESHADERPROGRAMVPROC  glCreateShaderProgramv ;
        MOTOR_OGL_API_CXX PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline ;
        MOTOR_OGL_API_CXX PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines ;
        MOTOR_OGL_API_CXX PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines ;
        MOTOR_OGL_API_CXX PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1IPROC  glProgramUniform1i ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1IVPROC  glProgramUniform1iv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv ;
        MOTOR_OGL_API_CXX PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv ;
        MOTOR_OGL_API_CXX PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline ;
        MOTOR_OGL_API_CXX PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d  ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv ;
        MOTOR_OGL_API_CXX PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer ;
        MOTOR_OGL_API_CXX PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv ;
        MOTOR_OGL_API_CXX PFNGLVIEWPORTARRAYVPROC glViewportArrayv ;
        MOTOR_OGL_API_CXX PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf ;
        MOTOR_OGL_API_CXX PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv ;
        MOTOR_OGL_API_CXX PFNGLSCISSORARRAYVPROC glScissorArrayv ;
        MOTOR_OGL_API_CXX PFNGLSCISSORINDEXEDPROC glScissorIndexed ;
        MOTOR_OGL_API_CXX PFNGLSCISSORINDEXEDVPROC glScissorIndexedv ;
        MOTOR_OGL_API_CXX PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv ;
        MOTOR_OGL_API_CXX PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed ;
        MOTOR_OGL_API_CXX PFNGLGETFLOATI_VPROC glGetFloati_v ;
        MOTOR_OGL_API_CXX PFNGLGETDOUBLEI_VPROC glGetDoublei_v ;

        #if 0
    }
}
#endif