
// auto generated by CMakeLists for header only libs
// this is required to have a Visual Studio attachable target
// see natus/cmake/configure/header_only.in.cpp

#include "api.h"

namespace natus
{
    namespace ntd
    {
        NATUS_NTD_API_C void ntd_export( void ) {}
    }
}
