
// auto generated by CMakeLists for header only libs
// this is required to have a Visual Studio attachable target
// see motor/cmake/configure/header_only.in.cpp

#include "api.h"

namespace motor
{
    namespace core
    {
        MOTOR_CORE_API_C void core_export( void ) {}
    }
}
