#
#
#

set( MOTOR_BUILD_ENV_CONFIGURED FALSE )

set( MOTOR_BUILD_ENV_MSVS OFF )
set( MOTOR_BUILD_ENV_MINGW OFF )
set( MOTOR_BUILD_ENV_CYGWIN OFF )
set( MOTOR_BUILD_ENV_MAKE OFF )

if( MSVC_IDE  )
    set( MOTOR_BUILD_ENV_MSVS ON )
endif()


set( MOTOR_BUILD_ENV_CONFIGURED TRUE )