
// auto generated by CMakeLists for header only libs
// this is required to have a Visual Studio attachable target
// see motor/cmake/configure/header_only.in.cpp

#include "api.h"

namespace motor
{
    namespace @lib_name@
    {
        MOTOR_@lib_name_upper@_API_C void @lib_name@_export( void ) {}
    }
}
